export const ABOUT_PAGES = {
    about: "List available internal Firefox pages",
    addons: "Manage extensions, themes, plugins, and updates",
    buildconfig: "Show build tools, options, and configuration",
    cache: "Inspect memory and disk network caches",
    certificate: "Browse stored certificates and their details",
    checkerboard: "Record and replay checkerboarding reports",
    compat: "Toggle Web Compatibility and SmartBlock fixes",
    config: "View and edit advanced preferences",
    crashes: "Review, submit, and clear crash reports",
    credits: "View Mozilla contributor credits",
    debugging: "Debug add-ons, tabs, workers, and remote Firefox",
    downloads: "View and manage downloaded files",
    firefoxview: "View recent browsing across windows and devices",
    home: "Open and customize Firefox Home",
    keyboard: "Customize Firefox keyboard shortcuts",
    license: "Read Firefox and third-party software licenses",
    logging: "Configure and capture diagnostic logging",
    logins: "Manage saved passwords and alerts",
    loginsimportreport: "Review the latest password import results",
    logo: "Display the branded Firefox logo",
    memory: "Measure, save, and reduce memory usage",
    mozilla: "Read the current Book of Mozilla verse",
    networking: "Inspect HTTP, sockets, DNS, and WebSockets",
    newtab: "Open Firefox Home's New Tab page",
    policies: "Inspect enterprise policies, errors, and documentation",
    preferences: "Manage Firefox settings",
    privatebrowsing: "Open the Private Browsing start page",
    processes: "Inspect process CPU and memory usage",
    profiles: "Manage Firefox profiles and profile folders",
    profiling: "Configure Firefox Profiler recording settings",
    protections: "Review privacy protections and blocked trackers",
    rights: "View Firefox legal rights and terms",
    robots: "View Firefox's robot-themed Easter egg",
    serviceworkers: "View and unregister registered service workers",
    studies: "View and remove Firefox studies",
    support: "View troubleshooting and system information",
    "sync-log": "Browse Firefox Sync log files",
    telemetry: "Inspect current and archived telemetry data",
    translations: "Translate text between supported languages",
    unloads: "Inspect and manually unload prioritized tabs",
    "url-classifier": "Inspect and test URL classification",
    webauthn: "Manage WebAuthn security tokens and credentials",
    webrtc: "Troubleshoot and inspect WebRTC calls",
    welcome: "Run Firefox's onboarding and setup flow",
} as const
