// AUTOGENERATED BY auto_lib.py
//
// Autogenerated message names for transparent context-forwarding wrappers
// created by auto_lib.py. Each of these corresponds to the wrapper for a
// single module.
//
// DO NOT EDIT


export type AutoLibForwardingToContent =
    | "UNUSED_SENTINEL"
    | "auto_lib_wrapper:src/content_auto/fillcmdline.ts->content"
    | "auto_lib_wrapper:src/content_auto/rss.ts->content"

export type AutoLibForwardingToBackground =
    | "UNUSED_SENTINEL"
    | "auto_lib_wrapper:src/background_auto/config_rc.ts->background"
    | "auto_lib_wrapper:src/background_auto/download_background.ts->background"
    | "auto_lib_wrapper:src/background_auto/clipboard.ts->background"
    | "auto_lib_wrapper:src/background_auto/open.ts->background"
    | "auto_lib_wrapper:src/background_auto/tabs.ts->background"

export type AutoLibForwardingToCommandline =
    | "UNUSED_SENTINEL"


