// AUTOGENERATED FROM src/background_auto/config_rc.ts BY auto_lib.py
//
// Automatically forwards invocations to the appropriate context (content
// script, background script, commandline iframe)
//
// DO NOT EDIT

import * as excmd_lib from "@src/lib/excmd_lib"
import * as _excmds from "@src/background_auto/config_rc.ts"
export default excmd_lib.forwardedToBackground("auto_lib_wrapper:src/background_auto/config_rc.ts->background", _excmds)
