// AUTOGENERATED FROM src/content_auto/fillcmdline.ts BY auto_lib.py
//
// Automatically forwards invocations to the appropriate context (content
// script, background script, commandline iframe)
//
// DO NOT EDIT

import * as excmd_lib from "@src/lib/excmd_lib"
import * as _excmds from "@src/content_auto/fillcmdline.ts"
export default excmd_lib.forwardedToContent("auto_lib_wrapper:src/content_auto/fillcmdline.ts->content", _excmds)
