#!/usr/bin/env bash

# stolen from https://gist.github.com/sindresorhus/7996717

changed_files="$(git diff-tree -r --name-only --no-commit-id $1 $2)"


file_changed() {
	echo "$changed_files" | grep --quiet "$1"
}

if file_changed package.json; then
	npm install
fi
