#!/bin/bash

source ./scripts/common

# Check if 'DEBUG = True' set in 'native_main.py'
if [[ "$(native_main_debug_flag)" != "False" ]]; then
  echo "Commit 'DEBUG = False' in 'native_main.py'"
  echo "Aborting Git commit ..."
  exit 1
fi

jsfiles=$(cachedFiles)

[ -z "$jsfiles" ] && exit 0

# Check if any of the files are ugly or contain a console.log call
consoleFiles=$(noisy $jsfiles)
uglyFiles=$(ugly $jsfiles)

if [ -n "$consoleFiles" ]; then
    echo "Warning: adding console.log calls in ${consoleFiles[@]}"
    echo 'Did you mean to use logger.debug?'
    echo
fi

if [ -n "$uglyFiles" ]; then
    echo "Prettify your files first:"
    echo 'npm run pretty'
    exit 1
fi

