#!/bin/bash

jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" "*.ts" "*.tsx" | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

# Check if any of the files are ugly
uglyFiles=()
for jsfile in $jsfiles; do
    diff "$jsfile" <($(npm bin)/prettier "$jsfile") >/dev/null || uglyFiles+=("$jsfile")
done

if [ -n $uglyFiles ]; then
    echo "Prettify your files first:"
    echo '$(npm bin)/prettier --write' "${uglyFiles[@]}"
    exit 1
fi
