#!/usr/bin/env bash

sign_and_submit() {
    (source AMOKEYS && web-ext sign -s build --api-key $AMOKEY --api-secret $AMOSECRET)
}

publish_beta() {
    npm run clean
    npm run build
    scripts/version beta
    sign_and_submit
}

publish_sideload() {
    npm run clean
    npm run build
    scripts/version beta
    sed 's/"name": "Tridactyl"/"name": "Tridactyl Sideload"/' -i build/manifest.json
    sed 's/tridactyl.vim@cmcaine/tridactyl.vim.betas@cmcaine/' -i build/manifest.json
    sign_and_submit
}

publish_stable() {
    npm run clean
    npm run build
    sign_and_submit
}

case $1 in
    stable) publish_stable;;
    *|beta) publish_beta;;
esac
