#!/bin/sh

mkdir -p ../build

# Links manifest.json into the build dir if it's not already there.
[ -e ../build/manifest.json ] || ln -sr manifest.json ../build/

# Watches the current directory's .tsc files for timestamp changes and
# compiles them to javascript.
tsc --outDir "../build" -w
